# Generated by Django 4.2.2 on 2023-06-19 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookarcpage', '0002_bookarcpage_book_series'),
        ('chapterpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterpage',
            name='book_arc_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='bookarcpage.bookarcpage'),
        ),
    ]
