# Generated by Django 4.2.2 on 2023-06-21 09:05

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chapterpage', '0002_chapterpage_book_arc_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterpage',
            name='chapter_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chapterpage',
            name='chapter_title',
            field=models.CharField(max_length=250),
        ),
    ]
