# Generated by Django 4.2.2 on 2023-06-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapterpage', '0003_alter_chapterpage_chapter_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterpage',
            name='next_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chapterpage.chapterpage'),
        ),
        migrations.AddField(
            model_name='chapterpage',
            name='previous_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chapterpage.chapterpage'),
        ),
    ]
