# Generated by Django 4.2.2 on 2023-06-21 10:28

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customhomepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='announcement',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='current',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
