# Generated by Django 4.2.2 on 2023-06-26 10:48

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customhomepage', '0003_bookarcpagechooser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookarcpagechooser',
            name='homepage',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='chooser_homepages', to='customhomepage.homepage'),
        ),
    ]
