# Generated by Django 4.2.2 on 2023-07-31 03:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookarcpage', '0004_rename_sumary_bookarcpage_summary'),
        ('series', '0005_series_current_info'),
        ('customhomepage', '0004_alter_bookarcpagechooser_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookarcpagechooser',
            name='bookarcpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bookarcpage.bookarcpage'),
        ),
        migrations.AlterField(
            model_name='bookarcpagechooser',
            name='homepage',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookarcpages', to='customhomepage.homepage'),
        ),
        migrations.CreateModel(
            name='SeriesChooser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriespages', to='customhomepage.homepage')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='series.series')),
            ],
            options={
                'unique_together': {('homepage', 'series')},
            },
        ),
    ]
