# Generated by Django 4.2.2 on 2023-06-18 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_alter_series_description'),
        ('bookarcpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookarcpage',
            name='book_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='series.series'),
        ),
    ]
