# Generated by Django 4.2.2 on 2023-06-21 09:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookarcpage', '0002_bookarcpage_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookarcpage',
            name='announcements',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookarcpage',
            name='sumary',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
