# Generated by Django 4.2.2 on 2023-06-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookarcpage', '0003_bookarcpage_announcements_bookarcpage_sumary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookarcpage',
            old_name='sumary',
            new_name='summary',
        ),
    ]
