# Generated by Django 4.2.2 on 2023-06-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('authorpage', '0002_authorpage_name'),
        ('series', '0002_seriespage_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeriesPage',
            new_name='Series',
        ),
    ]
