# Generated by Django 4.2.2 on 2023-06-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_rename_seriespage_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
