# Generated by Django 4.2.2 on 2023-06-21 09:58

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_alter_series_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='current_info',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
