# Generated by Django 4.2.2 on 2023-06-21 10:16

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorpage', '0002_authorpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='announcements',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
